server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true # 호스트명 대신 IP로 등록
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: apigateway-service
  # 라우팅 정보 등록
  cloud:
    gateway:
      server:
#        webmvc:
        webflux:
          default-filters:
            - name: GlobalFilter
              args:
                baseMessage: Spring Cloud Gateway Webflux Global Filter
                preLogger: true
                postLogger: true
          routes:
            - id: first-service
              uri: http://localhost:8081/
              predicates:
                - Path=/first-service/**
              # 필터 설정 - 프로퍼티
              filters:
#                - AddRequestHeader=f-request, 1st-request-header-by-yaml
#                - AddResponseHeader=f-response, 1st-response-header-from-yaml
                - CustomFilter
            - id: second-service
              uri: http://localhost:8082/
              predicates:
                - Path=/second-service/**
              # 필터 설정 - 프로퍼티
              filters:
#                - AddRequestHeader=s-request, 2nd-request-header-by-yaml
#                - AddResponseHeader=s-response, 2nd-response-header-from-yaml
                - CustomFilter
